networks:
  internal-pod:
    internal: true
  external-pod:
    internal: false

volumes:
  dolibarr-htdocs:
  dolibarr-custom:
  dolibarr-docs:
  mysql-data:

services:
  nginx:
    image: nginx
    ports:
      - 80:80
    volumes:
      - ./conf/nginx.conf:/etc/nginx/nginx.conf:ro
      - dolibarr-htdocs:/var/www/html:ro
      - dolibarr-custom:/var/www/html/custom:ro
    networks:
      - internal-pod
      - external-pod

  dolibarr:
    image: dolibarr/dolibarr:latest-fpm
    environment:
      DOLI_DB_HOST: "mysql"
      DOLI_DB_HOST_PORT: "3306"
      DOLI_DB_USER: "dolibarr"
      DOLI_DB_PASSWORD: "mysupersecretpasswordfordatabase"
      DOLI_DB_NAME: "dolibarr"
      DOLI_ADMIN_LOGIN: "admin"
      DOLI_ADMIN_PASSWORD: "mysuperhypersecretpasswordforadminacount"
    volumes:
      - dolibarr-docs:/var/www/documents
      - dolibarr-htdocs:/var/www/html
      - dolibarr-custom:/var/www/html/custom
    networks:
      - internal-pod

  mysql:
    image: mysql:latest
    environment:
      MYSQL_DATABASE: "dolibarr"
      MYSQL_USER: "dolibarr"
      MYSQL_PASSWORD: "mysupersecretpasswordfordatabase"
      MYSQL_ROOT_PASSWORD: "mysupersupersecretpasswordforrootuser"
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - internal-pod
