name: build
on:
  # can run job manually
  workflow_dispatch:
  # Run once a week
  schedule:
    - cron: '0 0 * * 6'

jobs:
  build-docker-images:
    strategy:
      matrix:
        dolibarr_version: [ 15.0.3, 16.0.5, 17.0.4, 18.0.6, 19.0.4, 20.0.4, develop ]
        os_version: [ ubuntu-24.04, ubuntu-24.04-arm ]
    runs-on: ${{ matrix.os_version }}
    steps:
      - uses: actions/checkout@v3
      - uses: docker/setup-buildx-action@v3
      - env:
          DOCKER_BUILD: 1
          DOCKER_PUSH: 0
        run: |
          echo secrets.DOCKER_HUB_USERNAME=${{ secrets.DOCKER_HUB_USERNAME }}
          echo ${{ secrets.DOCKER_HUB_PASSWORD }} | docker login -u ${{ secrets.DOCKER_HUB_USERNAME }} --password-stdin
          ./update.sh ${{ matrix.dolibarr_version }}

  update-readme:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
      - run: |
          echo secrets.DOCKER_HUB_USERNAME=${{ secrets.DOCKER_HUB_USERNAME }} 
          docker run --rm -t \
          -v $(pwd):/src \
          -e DOCKER_USER=${{ secrets.DOCKER_HUB_USERNAME }} \
          -e DOCKER_PASS=${{ secrets.DOCKER_HUB_PASSWORD }} \
          -e PUSHRM_PROVIDER=dockerhub \
          -e PUSHRM_FILE=/src/README.md \
          -e PUSHRM_SHORT='Docker image for Dolibarr ERP CRM Open source web suite.' \
          -e PUSHRM_TARGET=docker.io/dolibarr/dolibarr \
          -e PUSHRM_DEBUG=1 \
          chko/docker-pushrm:1
