name: update
on:
  # can run job manually
  workflow_dispatch:
  # Run once a week
  schedule:
    - cron: '30 23 * * 5'

jobs:
  build-docker-images:
    strategy:
      matrix:
        dolibarr_version: [ 15.0.3, 16.0.5, 17.0.4, 18.0.6, 19.0.4, 20.0.4, 21.0.0, develop ]
    runs-on: ubuntu-24.04
    steps:
      - env:
          DOCKER_BUILD: 0
          DOCKER_PUSH: 0
        run: |
          ./update.sh ${{ matrix.dolibarr_version }}
